name: "Trend Anti-Malware Scan Service Action"
description: "Scan files looking for malware using Trend Anti-Malware Scan Service"
inputs:
  CLOUD_ONE_API_KEY:
    description: "Cloud One API Key"
    required: true
  REGION:
    description: "Cloud One Region"
    required: true
    default: "us-1"
  FILES:
    description: "List of files to scan, space separated. If not provided, all files in the repository will be scanned."
    required: false
branding:
  icon: "package"
  color: "red"
runs:
  using: "docker"
  image: "docker://ghcr.io/raphabot/amaas:latest"
  args:
    - --api_key
    - ${{ inputs.CLOUD_ONE_API_KEY }}
    - --region
    - ${{ inputs.REGION }}
    - -f
    - $([ -z ${{ inputs.FILES }} ] && find . -type f -not -path "./.git/*" | tr '\n' ' ' || echo ${{ inputs.FILES }})